DROP TABLE administrators;
DROP TABLE batches;
DROP TABLE medicines;
DROP TABLE equipments;
DROP TABLE medical_files;
DROP TABLE consultations;
DROP TABLE health_records;
DROP TABLE lyceans_notification;
DROP TABLE lyceans_account;
DROP TABLE lyceans;
DROP TABLE health_personnels_notification;
DROP TABLE health_personnels_account;
DROP TABLE health_personnels